name: Build container images

on:
  push:
    branches:
      - main
  schedule:
    # Basically picked at random to try and be a low-load time for GitHub Actions
    - cron: '20 3 * * 0'
  workflow_dispatch:

jobs:
  build_push_images:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          # TODO use {{ github.repository_owner }} when https://github.com/redhat-actions/podman-login/issues/44 is fixed
          registry: ghcr.io/seagl

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Build and push container images
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./build-and-push.sh 24.04
